// <auto-generated />
using IoT_REST_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IoT_REST_API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190425135139_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IoT_REST_API.Models.Measurement", b =>
                {
                    b.Property<long>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MeasureDate")
                        .IsRequired();

                    b.Property<string>("MeasureTime")
                        .IsRequired();

                    b.Property<int>("Temperature");

                    b.Property<long>("TemperatureSensorId");

                    b.HasKey("MeasurementId");

                    b.HasIndex("TemperatureSensorId");

                    b.ToTable("Measurement");
                });

            modelBuilder.Entity("IoT_REST_API.Models.TemperatureSensor", b =>
                {
                    b.Property<long>("TemperatureSensorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceModel")
                        .IsRequired();

                    b.Property<string>("DeviceName")
                        .IsRequired();

                    b.Property<bool>("IsOnline");

                    b.Property<string>("LocationName")
                        .IsRequired();

                    b.HasKey("TemperatureSensorId");

                    b.ToTable("TemperatureSensor");
                });

            modelBuilder.Entity("IoT_REST_API.Models.Measurement", b =>
                {
                    b.HasOne("IoT_REST_API.Models.TemperatureSensor", "TemperatureSensor")
                        .WithMany("Measurements")
                        .HasForeignKey("TemperatureSensorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
